dataset:
  dataset_name: "ims"
  img_type: "MIDDLE_EAST_IR"
  seq_len: 25
  raw_seq_len: 45
  stride: 12
  layout: "THWC"
  raw_img_shape: [600, 600, 1]
  batch_layout: "NTHWC"
  ims_catalog: "/home/theator/leah/cloud-forecasting-transformer/datasets/ims/data_IR_NOT_RSS/CATALOG.csv"
  ims_data_dir: "/home/theator/leah/cloud-forecasting-transformer/datasets/ims/data_IR_NOT_RSS/data"
  start_date: [ 2018, 1, 1 ]
  train_val_split_date: [ 2022, 9, 1 ]
  train_test_split_date: [ 2023, 1, 1 ]
  end_date: [ 2023, 10, 1 ]
  time_delta: 15
  raw_time_delta: 15
  shuffle: true
  preprocess:
    grayscale: true
    crop:
      top: 200
      left: 200
      height: 384
      width: 384
    scale: true

optim:
  total_batch_size: 16
  micro_batch_size: 1
  num_workers: 12
  method: "adamw"
  lr: 0.00001
  wd: 0.0
  gradient_clip_val: 1.0
  max_epochs: 100
  # early stopping
  early_stop: true
  early_stop_mode: "min"
  early_stop_patience: 20
  # checkpoints
  save_top_k: 6
  skill_score:
    metrics_list: [ 'csi', 'mae', 'mse' ]
    threshold_list: [ 145, 160, 180, 200, 220 ]
    threshold_weights: null

logging:
  logging_prefix: "PredRNN_IMS"
  monitor_lr: true
  monitor_device: false
  track_grad_norm: -1
  monitor_mean_std: false
  use_tensorbaord: false
  use_csv: false
  use_wandb: true
  wandb:
    project: "predrnn"
  visualize:
    train_example_data_idx_list: [0, 10, 20 ,50]
    val_example_data_idx_list: [0, 10, 20, 50]
    test_example_data_idx_list: [0, 80, 160, 240, 320, 400]
    eval_example_only: false
    fs: 10
    figsize: [ 24, 8 ]
    plot_stride: 2
    cmap: "pysteps"

trainer:
  check_val_every_n_epoch: 1
  log_step_ratio: 0.001
  precision: 32
  accelerator: gpu

model:
  model_name: "predrnn"
  in_len: 13 # must have params.
  out_len: 12 # must have params.
  input_length: 13
  total_length: 25
  img_channel: 1
  img_width: 384
  num_hidden: [ 384, 384, 384, 384 ]
  filter_size: 5
  stride: 1
  patch_size: 12
  layer_norm: 0
  decouple_beta: 0.1
  injection_action: "concat"
  conv_on_input: 0
  res_on_conv: 0
  num_action_ch: 4
  reverse_input: 1
  reverse_scheduled_sampling: 0
  r_sampling_step_1: 25000
  r_sampling_step_2: 50000
  r_exp_alpha: 5000
  scheduled_sampling: 1
  sampling_stop_iter: 50000
  sampling_start_value: 1.0
  sampling_changing_rate: 0.00002
