dataset:
  dataset_name: "ims"
  img_type: "MIDDLE_EAST_IR"
  seq_len: 25
  raw_seq_len: 45
  stride: 12
  layout: "THWC"
  raw_img_shape: [600, 600, 1]
  batch_layout: "NTHWC"
  ims_catalog: "/home/theator/leah/cloud-forecasting-transformer/datasets/ims/data_IR_NOT_RSS/CATALOG.csv"
  ims_data_dir: "/home/theator/leah/cloud-forecasting-transformer/datasets/ims/data_IR_NOT_RSS/data"
  start_date: [ 2018, 1, 1 ]
  train_val_split_date: [ 2022, 9, 1 ]
  train_test_split_date: [ 2023, 1, 1 ]
  end_date: [ 2023, 10, 1 ]
  time_delta: 15
  raw_time_delta: 15
  shuffle: true
  preprocess:
    grayscale: true
    crop:
      top: 200
      left: 200
      height: 384
      width: 384
    scale: true

optim:
  total_batch_size: 24
  micro_batch_size: 1
  num_workers: 12
  method: "adamw"
  lr: 0.003
  wd: 0.0
  gradient_clip_val: 1.0
  max_epochs: 100
  # scheduler
  lr_scheduler_mode: "plateau"
  scheduler:
    mode: "min"
    factor: 0.1
    patience: 5
  # early stopping
  early_stop: true
  early_stop_mode: "min"
  early_stop_patience: 20
  # checkpoints
  save_top_k: 6
  skill_score:
    metrics_list: [ 'csi', 'mae', 'mse' ]
    threshold_list: [ 145, 160, 180, 200, 220 ]
    threshold_weights: null

logging:
  logging_prefix: "Rainformer_IMS"
  monitor_lr: true
  monitor_device: false
  track_grad_norm: -1
  monitor_mean_std: false
  use_tensorbaord: false
  use_csv: false
  use_wandb: true
  wandb:
    project: "rainformer"
  visualize:
    train_example_data_idx_list: [0, 10, 20 ,50]
    val_example_data_idx_list: [0, 10, 20, 50]
    test_example_data_idx_list: [0, 80, 160, 240, 320, 400]
    eval_example_only: false
    fs: 10
    figsize: [ 24, 8 ]
    plot_stride: 2
    cmap: "pysteps"

trainer:
  check_val_every_n_epoch: 1
  log_step_ratio: 0.001
  precision: 32
  accelerator: gpu

model:
  model_name: "rainformer"
  in_len: 13
  out_len: 12
  input_channel: 13
  output_channel: 12
  hidden_dim: 96
  downscaling_factors: [4, 2, 2, 2]
  layers: [2, 2, 2, 2]
  heads: [3, 6, 12, 24]
  head_dim: 32
  window_size: 12
  relative_pos_embedding: true
